// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShmsBackend.Data.Context;

#nullable disable

namespace ShmsBackend.Data.Migrations
{
    [DbContext(typeof(ShmsDbContext))]
    [Migration("20260623053012_RestructureFlatAndHouseEntities")]
    partial class RestructureFlatAndHouseEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Email");

                    b.ToTable("Admins", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Portal.Flat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Constituency")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlatName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("LandlordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FlatName")
                        .IsUnique();

                    b.HasIndex("LandlordId");

                    b.ToTable("Flats");
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Portal.House", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DepositFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HouseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OccupancyStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Vacant");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("NotPaid");

                    b.Property<decimal>("RentFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FlatId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Portal.PortalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Constituency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PortalUserType")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("PortalUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Accountant", b =>
                {
                    b.HasBaseType("ShmsBackend.Data.Models.Entities.Admin");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Accountants", (string)null);
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.AdminUser", b =>
                {
                    b.HasBaseType("ShmsBackend.Data.Models.Entities.Admin");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Manager", b =>
                {
                    b.HasBaseType("ShmsBackend.Data.Models.Entities.Admin");

                    b.Property<string>("ManagedDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeamSize")
                        .HasColumnType("int");

                    b.ToTable("Managers", (string)null);
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Secretary", b =>
                {
                    b.HasBaseType("ShmsBackend.Data.Models.Entities.Admin");

                    b.Property<string>("OfficeNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ToTable("Secretaries", (string)null);
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.SuperAdmin", b =>
                {
                    b.HasBaseType("ShmsBackend.Data.Models.Entities.Admin");

                    b.Property<string>("SuperAdminPermissions")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SuperAdmins", (string)null);
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Portal.Agent", b =>
                {
                    b.HasBaseType("ShmsBackend.Data.Models.Entities.Portal.PortalUser");

                    b.Property<string>("AgencyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Portal.Explorer", b =>
                {
                    b.HasBaseType("ShmsBackend.Data.Models.Entities.Portal.PortalUser");

                    b.ToTable("Explorers", (string)null);
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Portal.Landlord", b =>
                {
                    b.HasBaseType("ShmsBackend.Data.Models.Entities.Portal.PortalUser");

                    b.Property<string>("AgencyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Landlords", (string)null);
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Portal.Tenant", b =>
                {
                    b.HasBaseType("ShmsBackend.Data.Models.Entities.Portal.PortalUser");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Admin", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Admin", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Portal.Flat", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Portal.Landlord", "Landlord")
                        .WithMany()
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Portal.House", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Portal.Flat", "Flat")
                        .WithMany("Houses")
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flat");
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Accountant", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Admin", null)
                        .WithOne()
                        .HasForeignKey("ShmsBackend.Data.Models.Entities.Accountant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.AdminUser", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Admin", null)
                        .WithOne()
                        .HasForeignKey("ShmsBackend.Data.Models.Entities.AdminUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Manager", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Admin", null)
                        .WithOne()
                        .HasForeignKey("ShmsBackend.Data.Models.Entities.Manager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Secretary", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Admin", null)
                        .WithOne()
                        .HasForeignKey("ShmsBackend.Data.Models.Entities.Secretary", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.SuperAdmin", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Admin", null)
                        .WithOne()
                        .HasForeignKey("ShmsBackend.Data.Models.Entities.SuperAdmin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Portal.Agent", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Portal.PortalUser", null)
                        .WithOne()
                        .HasForeignKey("ShmsBackend.Data.Models.Entities.Portal.Agent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Portal.Explorer", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Portal.PortalUser", null)
                        .WithOne()
                        .HasForeignKey("ShmsBackend.Data.Models.Entities.Portal.Explorer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Portal.Landlord", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Portal.PortalUser", null)
                        .WithOne()
                        .HasForeignKey("ShmsBackend.Data.Models.Entities.Portal.Landlord", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Portal.Tenant", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Portal.PortalUser", null)
                        .WithOne()
                        .HasForeignKey("ShmsBackend.Data.Models.Entities.Portal.Tenant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Portal.Flat", b =>
                {
                    b.Navigation("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
