// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShmsBackend.Data.Context;

#nullable disable

namespace ShmsBackend.Data.Migrations
{
    [DbContext(typeof(ShmsDbContext))]
    partial class ShmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Accountant", b =>
                {
                    b.HasBaseType("ShmsBackend.Data.Models.Entities.Admin");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Accountants", (string)null);
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.AdminUser", b =>
                {
                    b.HasBaseType("ShmsBackend.Data.Models.Entities.Admin");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Manager", b =>
                {
                    b.HasBaseType("ShmsBackend.Data.Models.Entities.Admin");

                    b.Property<string>("ManagedDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TeamSize")
                        .HasColumnType("int");

                    b.ToTable("Managers", (string)null);
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Secretary", b =>
                {
                    b.HasBaseType("ShmsBackend.Data.Models.Entities.Admin");

                    b.Property<string>("OfficeNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ToTable("Secretaries", (string)null);
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.SuperAdmin", b =>
                {
                    b.HasBaseType("ShmsBackend.Data.Models.Entities.Admin");

                    b.Property<string>("SuperAdminPermissions")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SuperAdmins", (string)null);
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Accountant", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Admin", null)
                        .WithOne()
                        .HasForeignKey("ShmsBackend.Data.Models.Entities.Accountant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.AdminUser", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Admin", null)
                        .WithOne()
                        .HasForeignKey("ShmsBackend.Data.Models.Entities.AdminUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Manager", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Admin", null)
                        .WithOne()
                        .HasForeignKey("ShmsBackend.Data.Models.Entities.Manager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.Secretary", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Admin", null)
                        .WithOne()
                        .HasForeignKey("ShmsBackend.Data.Models.Entities.Secretary", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShmsBackend.Data.Models.Entities.SuperAdmin", b =>
                {
                    b.HasOne("ShmsBackend.Data.Models.Entities.Admin", null)
                        .WithOne()
                        .HasForeignKey("ShmsBackend.Data.Models.Entities.SuperAdmin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
